version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
      - ./.env:/app/.env
      - ./model_cache:/app/model_cache
    # environment:
    #   MODEL_CACHE_DIR: /app/model_cache
